language: java

sudo: required

jdk:
  - oraclejdk8

install: true

script:
 # Update to the latest java 8 version for full javafx support 
 - sudo apt-get update && sudo apt-get install oracle-java8-installer
 - java -version
 
 # Install a virtual frame buffer so that the screen isn't rendered
 - sudo apt-get install xvfb
 - Xvfb :99 &>/dev/null &
 - export DISPLAY=:99

 # Create gradle config file, adding non-used install4j application
 # path variable. This is used on developers computer.
 - mkdir -p $HOME/.gradle
 - echo 'install4jHomeDir=none' > $HOME/.gradle/gradle.properties
 
 # Build using Gradle
 # gradle build also runs the tests (both unit tests
 # and integration tests).
 - gradle build
 - gradle fatJar
